package ru.tsindrenko;

import com.google.gson.Gson;

import javax.swing.*;
import javax.swing.event.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;

public class GUI extends JFrame {
    //основа
    private JPanel rootPanel;
    private JTabbedPane tabbedPanel;
    private Gson gson;
    //чат
    private JButton sendButton;
    private JTextField inputMessageField;
    private JButton sendFileButton;
    private JTextArea chatWindow;
    private JList chatroomList;
    private JPanel chatPanel;
    private HashSet<String> chatrooms;
    //аккаунт
    private JPanel accountPanel;
    //контакты-создать чат
    private JPanel contactsPanel;
    private JScrollPane chatScroll;
    private JScrollPane chatListScroll;
    private JTextField nameTextField;
    private JButton createButton;
    private JCheckBox checkBoxDialog;
    private JLabel chatroomName;
    private JList participantsList;
    private JScrollPane participantsScroll;
    private JScrollPane searchScroll;
    private JLabel participantsLabel;
    private JButton makeParticipantButton;
    private HashMap<Integer, String> participants;
    private HashMap<String, Integer> searchResults;
    //контакты-найти пользователя
    private JList findList;
    private JTextField findTextField;
    private JLabel findLabel;
    private JButton findButton;
    //cлушатели
    ButtonEventListener buttonEventListener;
    ListEventListener listSelectionListener;
    KeyboardListener keyboardListener;
    //константы
    private final String userInfo = "USER";
    private final String chatroomInfo = "CHATROOM";
    private final String getRequest = "GET";
    private final String updateRequest = "UPDATE";
    private final String deleteRequest = "DELETE";
    private final String createRequest = "CREATE";

    GUI() {
        //основные настройки
        setContentPane(rootPanel);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setLocation(700, 350);
        setSize(600, 400);
        tabbedPanel.addChangeListener(new TabGUIChangeListener());
        gson = new Gson();
        //слушатели событий
        buttonEventListener = new ButtonEventListener();
        listSelectionListener = new ListEventListener();
        keyboardListener = new KeyboardListener();
        //настройки чата
        sendButton.addActionListener(buttonEventListener);
        sendFileButton.addActionListener(buttonEventListener);
        chatroomList.addListSelectionListener(listSelectionListener);
        inputMessageField.setFocusable(true);
        inputMessageField.addKeyListener(keyboardListener);
        //настройки контактов
        findList.addListSelectionListener(listSelectionListener);
        participantsList.addListSelectionListener(listSelectionListener);
        makeParticipantButton.addActionListener(buttonEventListener);
        findButton.addActionListener(buttonEventListener);
        createButton.addActionListener(buttonEventListener);
        participants = new HashMap<>();
        searchResults = new HashMap<>();
        chatrooms = new HashSet<>();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPanel = new JTabbedPane();
        rootPanel.add(tabbedPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        chatPanel = new JPanel();
        chatPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPanel.addTab("Чат", chatPanel);
        inputMessageField = new JTextField();
        inputMessageField.setText("");
        chatPanel.add(inputMessageField, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(302, 30), null, 0, false));
        sendButton = new JButton();
        sendButton.setText("Отправить");
        chatPanel.add(sendButton, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(302, 30), null, 0, false));
        sendFileButton = new JButton();
        sendFileButton.setText("Отправить файл");
        chatPanel.add(sendFileButton, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        chatScroll = new JScrollPane();
        chatPanel.add(chatScroll, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        chatWindow = new JTextArea();
        chatWindow.setEditable(false);
        chatWindow.setText("");
        chatScroll.setViewportView(chatWindow);
        chatListScroll = new JScrollPane();
        chatListScroll.putClientProperty("html.disable", Boolean.FALSE);
        chatPanel.add(chatListScroll, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        chatroomList = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        chatroomList.setModel(defaultListModel1);
        chatListScroll.setViewportView(chatroomList);
        accountPanel = new JPanel();
        accountPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPanel.addTab("Аккаунт", accountPanel);
        contactsPanel = new JPanel();
        contactsPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(7, 4, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPanel.addTab("Контакты", contactsPanel);
        searchScroll = new JScrollPane();
        contactsPanel.add(searchScroll, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 2, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        findList = new JList();
        final DefaultListModel defaultListModel2 = new DefaultListModel();
        findList.setModel(defaultListModel2);
        searchScroll.setViewportView(findList);
        chatroomName = new JLabel();
        chatroomName.setText("Название чата:");
        contactsPanel.add(chatroomName, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        findTextField = new JTextField();
        contactsPanel.add(findTextField, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        participantsScroll = new JScrollPane();
        contactsPanel.add(participantsScroll, new com.intellij.uiDesigner.core.GridConstraints(3, 3, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        participantsList = new JList();
        participantsScroll.setViewportView(participantsList);
        participantsLabel = new JLabel();
        participantsLabel.setText("Список участников:");
        contactsPanel.add(participantsLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        findButton = new JButton();
        findButton.setText("Найти");
        contactsPanel.add(findButton, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        createButton = new JButton();
        createButton.setText("Создать");
        contactsPanel.add(createButton, new com.intellij.uiDesigner.core.GridConstraints(6, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        checkBoxDialog = new JCheckBox();
        checkBoxDialog.setText("Диалог");
        contactsPanel.add(checkBoxDialog, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nameTextField = new JTextField();
        contactsPanel.add(nameTextField, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        findLabel = new JLabel();
        findLabel.setText("Поиск");
        contactsPanel.add(findLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        makeParticipantButton = new JButton();
        makeParticipantButton.setEnabled(true);
        makeParticipantButton.setText("<>");
        contactsPanel.add(makeParticipantButton, new com.intellij.uiDesigner.core.GridConstraints(3, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(60, 60), new Dimension(60, 60), new Dimension(60, 60), 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    public void sendMessageToSender(){
        int currentId = Main.messageReceiver.getCurrentChatID();
        TextMessage textMessage = new TextMessage(Sender.modifyText(inputMessageField.getText()), Main.user.getId(), Main.user.getNickname(), currentId, Main.databaseConnector.getChatroomName(currentId));
        Sender.sendMessage(gson.toJson(textMessage, TextMessage.class));
        inputMessageField.setText("");
    }

    class ButtonEventListener implements ActionListener {
        public void actionPerformed(ActionEvent e) {
            if (e.getSource().equals(sendButton) && !inputMessageField.getText().isEmpty()) {
                sendMessageToSender();
            } else if (e.getSource().equals(sendFileButton)) {
                JFileChooser fileopen = new JFileChooser();
                int ret = fileopen.showDialog(null, "Выбрать файл");
                if (ret == JFileChooser.APPROVE_OPTION) {
                    File file = fileopen.getSelectedFile();
                    Sender.sendFile(file, false);
                }
            } else if (e.getSource().equals(makeParticipantButton)) {
                updateParticipants();
            } else if (e.getSource().equals(createButton)) {
                createChatroom();
            } else if (e.getSource().equals(findButton)) {
                findUsers();
            }

        }
    }

    public void clearChatroomCreation() {
        //сохраняем данные
        chatrooms.add(nameTextField.getText());
        //Main.messageReceiver.setCurrentChatID(Main.databaseConnector.getChatroomID(nameTextField.getText()));
        System.out.println(Main.messageReceiver.getCurrentChatID());
        //восстанавливаем страницу
        createButton.setEnabled(true);
        nameTextField.setText("");
        checkBoxDialog.setSelected(false);
        participants.clear();
        participantsList.setListData(participants.values().toArray());
        findTextField.setText("");
        searchResults.clear();
        findList.setListData(searchResults.keySet().toArray());
        //работаем с основной страницей
        tabbedPanel.setSelectedComponent(chatPanel);
        chatroomList.removeListSelectionListener(listSelectionListener);
        chatroomList.setListData(chatrooms.toArray());
        chatroomList.addListSelectionListener(listSelectionListener);
        chatroomList.setSelectedValue(nameTextField.getText(), true);
    }

    public void createChatroom() {
        if (participants.size() < 2) {
            JOptionPane.showMessageDialog(null, "Нельзя создать комнату без собеседников");
        } else if (nameTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Название чата не должно быть пустым");
        } else {
            ChatRoom chatRoom = new ChatRoom(nameTextField.getText(), Main.user.getId(), checkBoxDialog.isSelected());
            chatRoom.getParticipants_id().addAll(participants.keySet());
            Sender.sendMessage(gson.toJson(new RequestMessage(chatroomInfo, createRequest, chatRoom)));
            createButton.setEnabled(false);
        }
    }

    public void findUsers() {
        if (!findTextField.getText().isEmpty()) {
            Sender.sendMessage(gson.toJson(new RequestMessage(userInfo, getRequest, findTextField.getText())));
        }
    }

    public void updateParticipants() {
        JList currentList = null;
        //обозначить текущий список
        if (findList.getSelectedValue() != null) {
            currentList = findList;
        } else if (participantsList.getSelectedValue() != null) {
            currentList = participantsList;
        } else {
            JOptionPane.showMessageDialog(null, "Выберите пользователя из списка");
        }

        //если пользователь выбран
        if (currentList != null) {
            //удалить из списка участников
            if (currentList.equals(participantsList)) {
                if (currentList.getSelectedValue().toString().equals(Main.user.getNickname())) {
                    JOptionPane.showMessageDialog(null, "Нельзя удалить себя из участников");
                } else {
                    participants.remove(searchResults.get(currentList.getSelectedValue().toString()));
                    participantsList.setListData(participants.values().toArray());
                    if (participants.size() <= 2) {
                        checkBoxDialog.setEnabled(true);
                    }
                }
            }
            //проверить, нет ли пользователя в списках
            else if (participants.values().contains(currentList.getSelectedValue().toString())) {
                JOptionPane.showMessageDialog(null, "Пользователь уже добавлен в участники");
            }

            //добавить пользователя
            else {
                participants.put(searchResults.get(currentList.getSelectedValue().toString()), currentList.getSelectedValue().toString());
                participantsList.setListData(participants.values().toArray());
                if (participants.size() > 2) {
                    checkBoxDialog.setEnabled(false);
                    checkBoxDialog.setSelected(false);
                }
            }
        }
    }

    public void fillChatroomList(List<Integer> chatrooms) {
        List<String> chatroomNames = new ArrayList<>();
        for (Integer chatroom : chatrooms) {
            chatroomNames.add(Main.databaseConnector.getChatroomName(chatroom));
        }
        this.chatrooms.addAll(chatroomNames);
        chatroomList.setListData(chatroomNames.toArray());
    }

    public void fillChatroomList() {
        if (!chatrooms.isEmpty()) {
            chatroomList.setListData(chatrooms.toArray());
        }
    }

    public void fillSearchList(HashMap<String, Integer> users) {
        findList.setListData(users.keySet().toArray());
        searchResults.putAll(users);
    }

    public JTextArea getChatWindow() {
        return chatWindow;
    }

    public HashMap<Integer, String> getParticipants() {
        return participants;
    }

    public void setParticipants(HashMap<Integer, String> participants) {
        this.participants = participants;
    }

    class ListEventListener implements ListSelectionListener {
        public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                if (e.getSource().equals(chatroomList)) {
                    int chatID = Main.databaseConnector.getChatroomID(chatroomList.getSelectedValue().toString());
                    System.out.println("CID: " + chatID);
                    Main.messageReceiver.setCurrentChatID(chatID);
                    chatWindow.setText("");
                    List<String> oldMessages = Main.databaseConnector.getMessages(chatID, true);
                    for (String message : oldMessages) {
                        chatWindow.append(message);
                    }
                    if (Main.messageQueue.containsKey(chatID)) {
                        chatWindow.append("*-----Новые сообщения-----*\n");
                        List<String> queuedMessages = Main.messageQueue.get(chatID);
                        for (String message : queuedMessages) {
                            chatWindow.append(message);
                        }
                        Main.messageQueue.remove(chatID);
                        Main.databaseConnector.setChatMessageRead(chatID);
                    }
                }
                if (e.getSource().equals(findList)) {
                    participantsList.clearSelection();
                } else if (e.getSource().equals(participantsList)) {
                    findList.clearSelection();
                }
            }
        }
    }

    class KeyboardListener implements KeyListener {
        @Override
        public void keyTyped(KeyEvent e) {
        }

        @Override
        public void keyPressed(KeyEvent e) {
        }

        @Override
        public void keyReleased(KeyEvent e) {
            if (e.getKeyCode() == KeyEvent.VK_ENTER && !inputMessageField.getText().isEmpty()) {
                sendMessageToSender();
            }
        }
    }

    class TabGUIChangeListener implements ChangeListener {
        public void stateChanged(ChangeEvent e) {
            if (tabbedPanel.getSelectedIndex() == 2) {
                if (participants.isEmpty()) {
                    participants.put(Main.user.getId(), Main.user.getNickname());
                }
                participantsList.setListData(participants.values().toArray());
            }
        }
    }

    public HashSet<String> getChatrooms() {
        return chatrooms;
    }
}
